services:
  frontend:
    image: todo-frontend-dev
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: todo-front-dev
    environment:
      - PORT=3001
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
  backend:
    image: todo-backend-dev
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: todo-back-dev
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:3456/the_database
      - REDIS_URL=redis://redis:3210
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:6.0.11
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    ports:
      - 3456:27017
    container_name: todo-mongo
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data
    ports:
      - 3210:6379
    container_name: todo-redis
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy
    depends_on:
      - frontend
      - backend



volumes:
  mongo_data:
  redis_data: