services:
  frontend:
    image: todo-frontend-dev
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: todo-front-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy
    depends_on:
      - frontend