version: '3.8'

services:
  server:
    image: phonebook-prod
    build: .
    container_name: phonebook-prod
    environment:
      - MONGODB_URL=mongodb://db_user:db_user_password@mongo:27017/phonebookDB
    ports:
      - 3001:3001
  mongo:
    image: mongo:6.0.11
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: phonebookDB
    volumes:
      - ./server/src/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: phonebook-mongo

volumes:
  mongo_data:
